<?php

$x = 123;
$y = 123.456;
print (number_format(124520325,2,".","-"));
echo "\n";
// print (rand(0,20));
// echo "\n";
// print (rand(0,20));
// echo "\n";
// print (rand(0,20));
// echo "\n";
// print (ceil($y));
// echo "\n";
// print (floor($y));
// echo "\n";
// print (round(145.34));
// echo "\n";
// print (round(145.74));
// echo "\n";
// print (sqrt(24));
// echo "\n";
// print(pow(2,8));
// echo "\n";
// print(is_nan(sin(0.34)) ? "is nan" : "is not nan");
// echo "\n";
// print(is_nan(asin(1.01)) ? "is nan" : "is not nan");
// echo "\n";
// print (pi());
// echo "\n";
// print (min(0,10,200,500,-300,-600,2.5,-3.5));
// echo "\n";
// print (max(0,10,200,500,-300,-600,2.5,-3.5));
// echo "\n";
// echo "\n";
// print(is_int($x) ? "is init" : "not init");
// echo "\n";
// print(is_int($y) ? "is init" : "not init");
// echo "\n";
// print(is_float($x) ? "is float" : "not float");
// echo "\n";
// print(is_float($y) ? "is float" : "not float");
// echo "\n";
// print (is_finite($x));
// echo "\n";
// print (is_finite($y));
// echo "\n";
// print(is_infinite($x));
// echo "\n";
// print(is_infinite($y));
// echo "\n";
// var_dump($x);
// echo "\n";
// var_dump($y);
// echo "\n";
// echo (PHP_INT_SIZE);
// echo "\n";
// echo (PHP_INT_MAX);
// echo "\n";
// echo (PHP_INT_MIN);
// echo "\n";
// echo (PHP_INT_SIZE);
// echo (PHP_FLOAT_MAX);
// echo "\n";
// echo (PHP_FLOAT_MIN);
// echo "\n";
// echo (PHP_FLOAT_DIG);
// echo "\n";
// echo (PHP_FLOAT_EPSILON);
// echo "\n";
